name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeding
        run: echo "Hellow World"
      - name: Print Goodbay
        run: echo "Done - bye!"
    
